name: Obtaining JWT to identify Action

on:
  push:
    branches: [ "**" ]

jobs:
  jwt:
    runs-on: ubuntu-24.04-arm
    container: 
      image: registry.xylonet.us/cavendish:latest
      credentials:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    steps:
    - with:
        entrypoint: /cnb/process/web --spring.main.web-application-type=none
