name: Obtaining JWT to identify Action

on:
  push:
    branches: [ "**" ]

jobs:
  jwt:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    steps:
    - name: Install OIDC Client from Core Package
      run: npm install @actions/core@1.6.0 @actions/http-client
    - name: Get Id Token
      uses: actions/github-script@v7
      id: idtoken
      with:
        script: |
          const coredemo = require('@actions/core')
          let id_token = await coredemo.getIDToken()
          core.exportVariable("ID_TOKEN", id_token)
    - name: Read ID Token from environment
      env:
        ACTIONS_STEP_DEBUG: true
      run: echo ${ID_TOKEN} >> token.txt